#218 chore: added (email) notifications
OpenSourceBrain/OSBv2 pull request #223
Opened 2021-07-01 15:20 UTC by zsinnema

2021-07-01 16:32 UTC, filippomc requested changes
needs some more work on exception handling

2021-07-01 16:32 UTC, filippomc commented on applications/workspaces/server/workspaces/service/notification/adapters/email_adapter.py
> +        smtp = smtplib.SMTP(EMAIL_HOST, EMAIL_PORT)
anything from here may easily fail and may break the main routine.

2021-07-01 16:32 UTC, filippomc commented on applications/workspaces/server/workspaces/repository/model_repository.py
> +        notify(
Better be catched and logged

2021-07-05 10:40 UTC, zsinnema commented
replaced by pr #231

2021-07-05 10:40 UTC, closed without merging