#211 allow github images with relative paths
OpenSourceBrain/OSBv2 pull request #234
Opened 2021-07-22 02:38 UTC by Muhaddatha

This commit allows GitHub images with relative paths to be displayed in the repository overview by converting an image html tag to a markdown image tag.

2021-07-22 06:56 UTC, zsinnema requested changes
imho this should be implemented in the python backend and not in the javascript frontend

2021-07-22 08:26 UTC, filippomc reviewed
The regex solution does not feel very robust. Why the [components api](https://github.com/remarkjs/react-markdown#appendix-b-components) wasn't used?

2021-07-22 08:28 UTC, filippomc commented
> imho this should be implemented in the python backend and not in the javascript frontend

This is a good idea. We could send html to the frontend directly so that any kind of description will be supported on the frontend side

2021-07-22 14:09 UTC, Muhaddatha commented
> The regex solution does not feel very robust. Why the [components api](https://github.com/remarkjs/react-markdown#appendix-b-components) wasn't used?

I thought I'd try the regex solution first since I had already implemented something similar and it worked. I agree, the components api would have been a better idea because it would lessen possible mistakes.

2021-07-23 08:13 UTC, filippomc approved these changes
I think we can leave as it is for now, what is done is done and will think about a backend solution once we start adding other repository types

2021-07-23 08:14 UTC, merged