Repo details page
OpenSourceBrain/OSBv2 pull request #660
Opened 2023-01-09 13:57 UTC by Aiga115

Issue 628
Finished with repository page details 

<img width="1440" alt="Screenshot 2023-01-31 at 3 45 17 PM" src="https://user-images.githubusercontent.com/32265731/215792154-e666995d-e5a6-4ba2-853c-9a72201db78b.png">

2023-01-10 16:41 UTC, Salam-Dalloul requested changes
Thanks @Aiga115 , great job, could you please fix the pr as discussed

2023-01-31 16:41 UTC, filippomc commented on applications/osb-portal/src/assets/images/workspace-banner.png:Zone.Identifier
> +[ZoneTransfer]
better remove this file

2023-01-31 16:42 UTC, filippomc commented on applications/osb-portal/src/assets/images/workspace-banner.png:Zone.Identifier
> +[ZoneTransfer]
also the related workspace-banner.png doesn't seem necessary

2023-01-31 16:50 UTC, filippomc commented on applications/osb-portal/src/pages/WorkspacePageTemperoray.tsx
> +import * as React from "react";
name typo

2023-02-02 19:09 UTC, merged